### ISSUE TITLE
Could not pass event SlimefunBlockPlaceEvent to HeadLimiter vDEV - 15

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun-Addon-Community/HeadLimiter#17]
slimefun and addons versions: https://prnt.sc/3jsBIq7QCeIq

my config: https://mclo.gs/CAPUITk

error: https://mclo.gs/giE3S5Y

this happens when I reach the limit of items per chunk

**Comment by J3fftw1** [comment]
fix in latest build
