### ISSUE TITLE
performance problems

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun-Addon-Community/HeadLimiter#20]
sf and addons: https://prnt.sc/XlVvJ5z9tEgv

performance problems: https://prnt.sc/UmPby4KgkKZ2

**Comment by J3fftw1** [comment]
Do you actually see performance hits about this?

**Comment by J3fftw1** [comment]
fixed in [8114960](https://github.com/Slimefun-Addon-Community/HeadLimiter/commit/8114960f4c2c0ae90158e771097b12decf160d87)
